#!/bin/bash

# TPC Attendance Dashboard - Quick Start Reference
# This file shows the most common startup scenarios

echo "==================================================="
echo "TPC Attendance Dashboard - Startup Reference Guide"
echo "==================================================="
echo ""
echo "DEVELOPMENT MODE (Debug)"
echo "========================"
echo "Used for: Local development, testing, hot reload"
echo "Command:  ./startup.sh debug"
echo "Runs on:  http://localhost:8000"
echo "Features:"
echo "  - Django development server"
echo "  - Auto-reload on file changes"
echo "  - Detailed error pages"
echo "  - DEBUG=True"
echo ""
echo "PRODUCTION MODE (Live)"
echo "======================"
echo "Used for: Ubuntu server deployment with auto-restart"
echo "Command:  ./startup.sh live"
echo "Runs on:  http://0.0.0.0:8000"
echo "Features:"
echo "  - Gunicorn WSGI server"
echo "  - Multiple worker processes (4 default)"
echo "  - Threaded worker for better performance"
echo "  - DEBUG=False (secure)"
echo "  - Logging to logs/gunicorn*.log"
echo ""
echo "SYSTEMD AUTO-START (Ubuntu Server)"
echo "===================================="
echo "Setup commands:"
echo "  1. sudo cp tpc-attendance.service /etc/systemd/system/"
echo "  2. sudo systemctl daemon-reload"
echo "  3. sudo systemctl enable tpc-attendance.service"
echo "  4. sudo systemctl start tpc-attendance.service"
echo ""
echo "Manage service:"
echo "  sudo systemctl status tpc-attendance.service      # Check status"
echo "  sudo systemctl start tpc-attendance.service       # Start"
echo "  sudo systemctl stop tpc-attendance.service        # Stop"
echo "  sudo systemctl restart tpc-attendance.service     # Restart"
echo "  sudo journalctl -u tpc-attendance.service -f      # View logs"
echo ""
echo "WHAT HAPPENS AT STARTUP"
echo "======================="
echo "✓ Virtual environment setup (if needed)"
echo "✓ Dependencies installation"
echo "✓ Environment file configuration"
echo "✓ DATABASE MIGRATIONS (automatic)"
echo "✓ Static files collection"
echo "✓ Redis service check/start"
echo "✓ Celery worker startup"
echo "✓ Celery beat scheduler startup"
echo "✓ Web server startup (Django or Gunicorn)"
echo ""
echo "IMPORTANT: Migrations run automatically before server starts"
echo ""
echo "LOG FILES"
echo "========="
echo "Location: ./logs/"
echo "  - celery.log              Celery worker output"
echo "  - celery_beat.log         Celery scheduler output"
echo "  - gunicorn.log            Gunicorn server (if using live mode)"
echo "  - gunicorn_access.log     HTTP requests log"
echo "  - gunicorn_error.log      HTTP errors log"
echo ""
echo "View logs:"
echo "  tail -f logs/gunicorn.log"
echo "  tail -f logs/celery.log"
echo ""
echo "ENVIRONMENT CONFIGURATION"
echo "========================="
echo "Edit: .env file in project root"
echo ""
echo "For DEBUG mode (.env):"
echo "  DEBUG=True"
echo "  DB_ENGINE=django.db.backends.sqlite3  (or PostgreSQL)"
echo ""
echo "For LIVE mode (.env):"
echo "  DEBUG=False"
echo "  SECRET_KEY=<secure-random-key>"
echo "  ALLOWED_HOSTS=yourdomain.com,127.0.0.1"
echo "  DB_ENGINE=django.db.backends.postgresql"
echo ""
echo "QUICK TROUBLESHOOTING"
echo "===================="
echo "Database not synced?"
echo "  python manage.py migrate --verbosity 3"
echo ""
echo "Port 8000 in use?"
echo "  sudo lsof -i :8000  # Find process"
echo "  sudo kill -9 <PID>  # Kill it"
echo ""
echo "Service won't start?"
echo "  sudo journalctl -u tpc-attendance.service -f  # Check logs"
echo "  ./startup.sh live                              # Test manually"
echo ""
echo "Redis not running?"
echo "  redis-cli ping                 # Test connection"
echo "  redis-server --daemonize yes   # Start in background"
echo ""
echo "For more information, see UBUNTU_SETUP.md"
echo "==================================================="
